In [7]:
import numpy as np

from sklearn.model_selection import KFold
from sklearn.neighbours import KNeighboursClassifier

In [19]:
classes = []
pred = []
with open('wine.data') as inp:
    for line in inp:
        classes.append(int(line[:-1].split(',')[0]))
        pred.append([float(n) for n in line[:-1].split(',')[1:]])

In [20]:
classes = np.array(classes)
pred = np.array(pred)

In [21]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [22]:
folds = kfold.split(pred)
n_neighbours = 5
for train_index, test_index in folds:
    pred_train, pred_test = pred[train_index], pred[test_index]
    classes_train, classes_test = classes[train_index], classes[test_index]
    

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3]
[1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3]
[1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3]
[1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]
[1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3]
